name: Build and Publish Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: NPM Build and Test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: Tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: Publish
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish
